-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."authorization"
(
    user_id integer NOT NULL,
    acess_token_id smallint NOT NULL,
    acess_token_key character varying(128) COLLATE pg_catalog."default" NOT NULL,
    acess_token_expires timestamp with time zone NOT NULL,
    refresh_token character varying(128) COLLATE pg_catalog."default" NOT NULL,
    refresh_token_expires timestamp with time zone NOT NULL,
    CONSTRAINT authorization_pkey PRIMARY KEY (user_id, acess_token_id)
);

CREATE TABLE IF NOT EXISTS public."user"
(
    id serial NOT NULL,
    username character varying(32) COLLATE pg_catalog."default" NOT NULL,
    email character varying(128) COLLATE pg_catalog."default" NOT NULL,
    password character varying(72) COLLATE pg_catalog."default",
    first_name character varying(24) COLLATE pg_catalog."default",
    last_name character varying(24) COLLATE pg_catalog."default",
    phone character varying(24) COLLATE pg_catalog."default",
    CONSTRAINT user_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_role
(
    user_id integer NOT NULL,
    role_role_id integer NOT NULL,
    CONSTRAINT user_role_pkey PRIMARY KEY (user_id, role_role_id)
);

CREATE TABLE IF NOT EXISTS public.role
(
    role_id serial NOT NULL,
    role_name character varying(32) COLLATE pg_catalog."default" NOT NULL,
    role_description character varying(256) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT role_pkey PRIMARY KEY (role_id)
);

CREATE TABLE IF NOT EXISTS public.following
(
    user_id integer NOT NULL,
    user_id_following integer NOT NULL,
    CONSTRAINT "following _pkey" PRIMARY KEY (user_id, user_id_following)
);

CREATE TABLE IF NOT EXISTS public.post
(
    id character(22) COLLATE pg_catalog."default" NOT NULL,
    user_id integer NOT NULL,
    created timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    text character varying(256) COLLATE pg_catalog."default" NOT NULL,
    score bigint NOT NULL DEFAULT 0,
    post_parent_id character(22) COLLATE pg_catalog."default",
    CONSTRAINT post_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.vote
(
    user_id integer NOT NULL,
    post_id character(22) COLLATE pg_catalog."default" NOT NULL,
    positive boolean NOT NULL DEFAULT true,
    CONSTRAINT vote_pkey PRIMARY KEY (user_id, post_id)
);

CREATE TABLE IF NOT EXISTS public.password_reset
(
    user_id integer NOT NULL,
    mail_key character(22) NOT NULL,
    reset_key character(22) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ip cidr NOT NULL,
    PRIMARY KEY (user_id, mail_key)
);

ALTER TABLE IF EXISTS public."authorization"
    ADD FOREIGN KEY (user_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.user_role
    ADD FOREIGN KEY (role_role_id)
    REFERENCES public.role (role_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.user_role
    ADD FOREIGN KEY (user_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.following
    ADD FOREIGN KEY (user_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.following
    ADD FOREIGN KEY (user_id_following)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.post
    ADD FOREIGN KEY (post_parent_id)
    REFERENCES public.post (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL
    NOT VALID;


ALTER TABLE IF EXISTS public.post
    ADD FOREIGN KEY (user_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.vote
    ADD FOREIGN KEY (post_id)
    REFERENCES public.post (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.vote
    ADD FOREIGN KEY (user_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.password_reset
    ADD FOREIGN KEY (user_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;

END;